# Generated by Django 5.0.14 on 2026-02-05 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('donate', 'Donate'), ('sell', 'Sell')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('baby_gender', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('unisex', 'Unisex')], max_length=10)),
                ('age_range', models.CharField(choices=[('0-3m', '0-3 months'), ('3-6m', '3-6 months'), ('6-12m', '6-12 months'), ('1-2y', '1-2 years'), ('2-3y', '2-3 years'), ('3-4y', '3-4 years'), ('4-5y', '4-5 years'), ('5+y', '5+ years')], max_length=10)),
                ('size', models.CharField(help_text='e.g., 6M, 12M, 2T', max_length=50)),
                ('condition', models.CharField(choices=[('new', 'Like New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in BDT (only for sell items)', max_digits=10, null=True)),
                ('area', models.CharField(help_text='Area or location', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('done', 'Done')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
