# Generated by Django 5.0.14 on 2026-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_item_image_item_image1_item_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='area_details',
            field=models.CharField(blank=True, help_text='e.g., Road 01, House 20, Block A', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='area',
            field=models.CharField(choices=[('mirpur', 'Mirpur'), ('uttara', 'Uttara'), ('dhanmondi', 'Dhanmondi'), ('gulshan', 'Gulshan'), ('banani', 'Banani'), ('mohammadpur', 'Mohammadpur'), ('badda', 'Badda'), ('rampura', 'Rampura'), ('motijheel', 'Motijheel'), ('farmgate', 'Farmgate'), ('other', 'Other')], help_text='Select your area', max_length=50),
        ),
    ]
