# Generated by Django 5.0.14 on 2026-02-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_item_area_details_alter_item_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='area_details',
        ),
        migrations.AddField(
            model_name='item',
            name='detailed_address',
            field=models.CharField(blank=True, help_text='e.g., Road 01, House 20, Block A', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='area',
            field=models.CharField(choices=[('mirpur', 'Mirpur'), ('mohammadpur', 'Mohammadpur'), ('uttara', 'Uttara'), ('dhanmondi', 'Dhanmondi')], help_text='Select your area', max_length=50),
        ),
    ]
