# Generated by Django 5.0.14 on 2026-02-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_item_area_details_item_detailed_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alternative_contact_name',
            field=models.CharField(blank=True, help_text='e.g., Guard, House Helper, Family Member', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='alternative_contact_phone',
            field=models.CharField(blank=True, help_text='Alternative phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='use_alternative_contact',
            field=models.BooleanField(default=False, help_text='Use different contact for this item'),
        ),
    ]
