"""
Django settings for LittleLoop project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*7lj7q)1@oe^#fe$$8%o)4e8w$hbgg=h&e(!mw01l6r%kc756b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom apps
    'accounts',  # User accounts & profile management
    'listings',  # Baby clothes listings (donate/sell)
]

# Add Cloudinary apps only in production (when cloudinary credentials are set)
if os.environ.get('CLOUDINARY_CLOUD_NAME'):
    INSTALLED_APPS.insert(6, 'cloudinary_storage')  # Before custom apps
    INSTALLED_APPS.insert(7, 'cloudinary')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection and translation
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Project-level templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Database - Simple local PostgreSQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'littleloop',
#         'USER': 'postgres', 
#         'PASSWORD': 'admin',
#         'HOST': 'localhost',
#         'PORT': '5433',
#     }
# }

# DATABASES["default"] = dj_database_url.parse("postgresql://littleloop_195m_user:F4qeloPuFTwINFLtELxkvw1wqdVU3736@dpg-d65dliogjchc73bhge20-a.oregon-postgres.render.com/littleloop_195m")
# Database Configuration
# Works both locally and on Render
DATABASES = {
    "default": dj_database_url.config(
        default='postgresql://postgres:admin@localhost:5433/littleloop',  # Local default
        conn_max_age=600,
        ssl_require=False,  # SSL not needed for local
    )
}

# Enable SSL only for production (when DATABASE_URL is set)
if 'DATABASE_URL' in os.environ:
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'  # English as default language

# Supported languages
LANGUAGES = [
    ('en', 'English'),  # English
    ('bn', 'বাংলা'),  # Bangla
]

# Translation files directory
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Dhaka'  # Bangladesh timezone

USE_I18N = True  # Enable internationalization

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (User uploads - profile pictures, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary Configuration (for persistent media storage in production)
# Get credentials from: https://cloudinary.com/console
# Only configure if credentials are present (production)
if os.environ.get('CLOUDINARY_CLOUD_NAME'):
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    }
    # Use Cloudinary for media files in production
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication backend - Custom email/phone authentication
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrPhoneBackend',  # Custom email/phone authentication
    'django.contrib.auth.backends.ModelBackend',  # Fallback for admin
]

# Redirect URLs
LOGIN_URL = '/profile/login/'  # Redirect to login page
LOGOUT_REDIRECT_URL = '/'  # Redirect to homepage
